#!/bin/bash

set -e

PORT=$1

if [ -z $PORT ]
then
	echo "use: devflash <port>"
	exit 1
fi

mos build --verbose --local
mos flash --port $PORT

RESTART="$0 $@"
restart() {
	$RESTART
}

trap restart INT
mos console --port $PORT
